### ISSUE TITLE
run tests html 

### ISSUE THREAD

**Issue by wadelee1986** [LeonardoVal/ludorum.js#2]
Could you please tell me how to run tests html file.

**Comment by LeonardoVal** [comment]
Test are run with [grunt](https://gruntjs.com/). You can install it with `npm -g install grunt-cli` and then running `grunt` in the project's root.
The project includes some HTML pages which are used for _playtesting_ and trying out simple code snippets. You don't need to build the project for this, but you must install the project's dependencies, with `npm i`.
